'use client';import{useState}from'react';import{motion}from'framer-motion';import{CalendarDays,Clock,CheckCircle,Loader2}from'lucide-react';
declare global{interface Window{emailjs:any;}}
const SL=[{l:'12:00 PM',v:'12:00'},{l:'1:00 PM',v:'13:00'},{l:'2:00 PM',v:'14:00'},{l:'7:00 PM',v:'19:00'},{l:'8:00 PM',v:'20:00'},{l:'9:00 PM',v:'21:00'}],MX=5;
function gid(){return'RN'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).substring(2,6).toUpperCase();}
function sk(d:any,t:any){return'rn_'+d+'_'+t;}
function gb(d:any,t:any){try{return JSON.parse(localStorage.getItem(sk(d,t))||'[]');}catch{return[];}}
function sb(d:any,t:any,v:any){const b=gb(d,t);b.push(v);localStorage.setItem(sk(d,t),JSON.stringify(b));}
function ga(d:any,t:any){const b=gb(d,t);return{f:b.length>=MX,r:MX-b.length};}
function se(b:any){try{if(typeof window!=='undefined'&&window.emailjs)window.emailjs.send('YOUR_SERVICE_ID','YOUR_TEMPLATE_ID',{booking_id:b.id,to_email:'yuvrajanand9799@gmail.com',customer_name:b.n,customer_phone:b.p,customer_email:b.e,booking_date:b.d,booking_time:b.t,guests:b.g,special_requests:b.s||'None'},'YOUR_PUBLIC_KEY');}catch{}}
export default function BP(){const[st,setSt]=useState('f');const[ld,setLd]=useState(false);const[bi,setBi]=useState('');const[f,setF]=useState({n:'',p:'',e:'',d:'',t:'',g:'2',sr:''});const[er,setEr]=useState<any>({});const td=new Date().toISOString().split('T')[0];
function v(){const e:any={};if(!f.n.trim())e.n='Req';if(!f.p.trim())e.p='Req';else if(!/^[0-9+\-\s]{7,15}$/.test(f.p))e.p='Bad';if(!f.e.trim())e.e='Req';else if(!f.e.includes('@'))e.e='Bad';if(!f.d)e.d='Req';if(!f.t)e.t='Req';setEr(e);return Object.keys(e).length===0;}
function h(e:React.FormEvent){e.preventDefault();if(!v())return;const id=gid();setBi(id);const bk:any={id,n:f.n,p:f.p,e:f.e,d:f.d,t:f.t,g:f.g,s:f.sr};setLd(true);setTimeout(()=>{sb(f.d,f.t,bk);se(bk);setLd(false);setSt('c');},800);}
if(st==='c')return(<div className="pt-20 min-h-screen flex items-center justify-center p-4"><motion.div initial={{opacity:0,scale:0.9}} animate={{opacity:1,scale:1}} className="card p-8 md:p-12 text-center max-w-md"><CheckCircle className="w-20 h-20 text-success mx-auto mb-6"/><h2 className="mb-2">Booking Confirmed!</h2><p className="text-text-muted mb-4">Your table has been reserved.</p><div className="bg-primary/5 rounded-2xl p-6 mb-6 border-2 border-primary/10"><p className="text-xs text-text-muted mb-1">Booking ID</p><p className="text-2xl font-bold text-primary font-mono tracking-wider">{bi}</p></div><a href="/" className="btn-primary w-full justify-center">Back to Home</a></motion.div></div>);
return(<div className="pt-20"><section className="bg-primary py-16"><div className="container-custom text-center"><motion.h1 className="text-white mb-4" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>Book a Table</motion.h1><motion.p className="text-white/80 max-w-2xl mx-auto" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:0.1}}>Reserve at ReNorth</motion.p></div></section><section className="section-padding"><div className="container-custom"><div className="max-w-3xl mx-auto"><form onSubmit={h} className="card p-6 md:p-8 space-y-6">{Object.keys(er).length>0&&<div className="bg-error/10 text-error p-4 rounded-lg text-sm">Fix errors.</div>}
<div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div><label className="block text-sm font-medium mb-2">Name *</label><input value={f.n} onChange={e=>setF({...f,n:e.target.value})} className={"input-field "+(er.n?'border-error':'')} placeholder="Name"/>{er.n&&<p className="text-error text-xs mt-1">{er.n}</p>}</div>
<div><label className="block text-sm font-medium mb-2">Phone *</label><input value={f.p} onChange={e=>setF({...f,p:e.target.value})} className={"input-field "+(er.p?'border-error':'')} placeholder="Phone"/>{er.p&&<p className="text-error text-xs mt-1">{er.p}</p>}</div>
<div><label className="block text-sm font-medium mb-2">Email *</label><input type="email" value={f.e} onChange={e=>setF({...f,e:e.target.value})} className={"input-field "+(er.e?'border-error':'')} placeholder="Email"/>{er.e&&<p className="text-error text-xs mt-1">{er.e}</p>}</div>
<div><label className="block text-sm font-medium mb-2">Date *</label><input type="date" min={td} value={f.d} onChange={e=>setF({...f,d:e.target.value,t:''})} className={"input-field "+(er.d?'border-error':'')}/>{er.d&&<p className="text-error text-xs mt-1">{er.d}</p>}</div>
<div><label className="block text-sm font-medium mb-2">Guests *</label><select value={f.g} onChange={e=>setF({...f,g:e.target.value})} className="input-field">{Array.from({length:20},(_,i)=>i+1).map(n=><option key={n} value={n}>{n}</option>)}</select></div></div>
<div><label className="block text-sm font-medium mb-3"><Clock className="w-4 h-4 inline mr-1"/>Time *</label>{f.d?(<div className="grid grid-cols-2 md:grid-cols-3 gap-3">{SL.map(s=>{const a=ga(f.d,s.v);return(<button key={s.v} type="button" disabled={a.f} onClick={()=>setF({...f,t:s.v})} className={`p-4 rounded-xl text-sm font-semibold transition-all border-2 ${a.f?'bg-gray-100 text-gray-300 border-gray-200 cursor-not-allowed':f.t===s.v?'bg-primary text-white border-primary':'bg-white text-text border-border hover:border-primary'}`}><div>{s.l}</div><div className={"text-xs mt-1 "+(a.f?'text-gray-300':'text-text-muted')}>{a.f?'Full':a.r+' left'}</div></button>);})}</div>):<p className="text-text-muted text-sm">Select date first</p>}{er.t&&<p className="text-error text-xs mt-1">{er.t}</p>}</div>
<div><textarea className="input-field" rows={3} value={f.sr} onChange={e=>setF({...f,sr:e.target.value})} placeholder="Special requests (optional)"/></div>
<button type="submit" disabled={ld||!f.t} className="btn-primary w-full justify-center text-base py-4">{ld?<><Loader2 className="w-5 h-5 animate-spin"/>Confirming...</>:<><CalendarDays className="w-5 h-5"/>Confirm Booking</>}</button></form></div></div></section></div>);}