module.exports = {
    "dishes": [
        // Starters
        { "name": "Paneer Tikka", "description": "Smoked cottage cheese marinated with aromatic spices and grilled in tandoor", "category": "starters", "price": 325, "isVeg": true, "isChefSpecial": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?paneer+tikka,indian+food" },
        { "name": "Tandoori Chicken", "description": "Chicken marinated in yogurt and spices, chargrilled in clay oven", "category": "starters", "price": 425, "isVeg": false, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?tandoori+chicken,indian+food" },
        { "name": "Hara Bhara Kebab", "description": "Spinach and potato patties with green herbs, shallow fried", "category": "starters", "price": 295, "isVeg": true, "image": "https://source.unsplash.com/400x300/?hara+bhara+kebab,indian+food" },
        { "name": "Chicken Seekh Kebab", "description": "Minced chicken skewers with fresh herbs and Indian spices", "category": "starters", "price": 395, "isVeg": false, "image": "https://source.unsplash.com/400x300/?chicken+seekh+kebab,indian+food" },
        { "name": "Malai Broccoli", "description": "Broccoli florets in creamy cashew marinade, grilled to perfection", "category": "starters", "price": 345, "isVeg": true, "image": "https://source.unsplash.com/400x300/?malai+broccoli,indian+food" },
        { "name": "Crispy Corn", "description": "Golden fried corn kernels tossed with peppers and chaat masala", "category": "starters", "price": 275, "isVeg": true, "image": "https://source.unsplash.com/400x300/?crispy+corn,indian+food" },
        { "name": "Dahi Ke Kebab", "description": "Crispy yogurt kebabs with nuts and raisins, melt-in-mouth", "category": "starters", "price": 315, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?dahi+kebab,indian+food" },
        { "name": "Amritsari Fish", "description": "Crispy fried fish marinated with gram flour and Punjabi spices", "category": "starters", "price": 445, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?amritsari+fish,indian+food" },
        { "name": "Tandoori Prawns", "description": "Jumbo prawns marinated in yogurt and spices, chargrilled", "category": "starters", "price": 525, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?tandoori+prawns,indian+food" },
        { "name": "Mushroom Galouti", "description": "Melt-in-mouth mushroom kebabs with royal Awadhi spices", "category": "starters", "price": 375, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?mushroom+galouti,indian+food" },
        { "name": "Chicken 65", "description": "Crispy fried chicken tossed in fiery South Indian spice mix", "category": "starters", "price": 395, "isVeg": false, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?chicken+65,indian+food" },
        { "name": "Samosa Chaat", "description": "Crushed samosas topped with yogurt, chutneys and sev", "category": "starters", "price": 245, "isVeg": true, "image": "https://source.unsplash.com/400x300/?samosa+chaat,indian+food" },
        { "name": "Aloo Tikki", "description": "Crispy potato patties with spiced chickpeas and chutneys", "category": "starters", "price": 225, "isVeg": true, "image": "https://source.unsplash.com/400x300/?aloo+tikki,indian+food" },
        { "name": "Papdi Chaat", "description": "Crispy wafers with yogurt, chutneys and pomegranate", "category": "starters", "price": 235, "isVeg": true, "image": "https://source.unsplash.com/400x300/?papdi+chaat,indian+food" },
        { "name": "Bharwan Mushrooms", "description": "Stuffed mushrooms with spiced cheese and herbs, grilled", "category": "starters", "price": 365, "isVeg": true, "image": "https://source.unsplash.com/400x300/?bharwan+mushroom,indian+food" },
        { "name": "Mutton Seekh Kebab", "description": "Minced lamb skewers with fresh mint and Indian spices", "category": "starters", "price": 475, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?mutton+seekh+kebab,indian+food" },
        { "name": "Chilli Paneer", "description": "Indo-Chinese style paneer tossed with peppers and soy glaze", "category": "starters", "price": 325, "isVeg": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?chilli+paneer,indian+food" },
        { "name": "Tandoori Momos", "description": "Steamed dumplings tossed in tandoori masala and chargrilled", "category": "starters", "price": 295, "isVeg": true, "image": "https://source.unsplash.com/400x300/?tandoori+momos,indian+food" },
        { "name": "Achari Chicken Tikka", "description": "Chicken tikka marinated in pickling spices and chargrilled", "category": "starters", "price": 425, "isVeg": false, "image": "https://source.unsplash.com/400x300/?achari+chicken+tikka,indian+food" },
        { "name": "Kasundi Fish Tikka", "description": "Fish tikka in tangy mustard marinade, grilled in tandoor", "category": "starters", "price": 465, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?kasundi+fish+tikka,indian+food" },

        // Mains
        { "name": "Butter Chicken", "description": "Signature creamy tomato-based curry with tender tandoori chicken", "category": "mains", "price": 495, "isVeg": false, "isChefSpecial": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?butter+chicken,indian+food" },
        { "name": "Chicken Tikka Masala", "description": "Grilled chicken tikka simmered in rich spiced tomato gravy", "category": "mains", "price": 475, "isVeg": false, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?chicken+tikka+masala,indian+food" },
        { "name": "Kadhai Chicken", "description": "Chicken cooked with bell peppers in rustic kadhai masala", "category": "mains", "price": 465, "isVeg": false, "image": "https://source.unsplash.com/400x300/?kadhai+chicken,indian+food" },
        { "name": "Chicken Chettinad", "description": "Fiery South Indian chicken curry with roasted spices and coconut", "category": "mains", "price": 485, "isVeg": false, "image": "https://source.unsplash.com/400x300/?chicken+chettinad,indian+food" },
        { "name": "Mutton Rogan Josh", "description": "Kashmiri-style lamb curry with aromatic spices and yogurt", "category": "mains", "price": 575, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?mutton+rogan+josh,indian+food" },
        { "name": "Mutton Keema", "description": "Spiced minced lamb cooked with green peas and fresh herbs", "category": "mains", "price": 525, "isVeg": false, "image": "https://source.unsplash.com/400x300/?mutton+keema,indian+food" },
        { "name": "Laal Maas", "description": "Fiery Rajasthani lamb curry with red chillies and ghee", "category": "mains", "price": 595, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?laal+maas,indian+food" },
        { "name": "Dal Makhani", "description": "Slow-cooked black lentils with cream and butter", "category": "mains", "price": 325, "isVeg": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?dal+makhani,indian+food" },
        { "name": "Dal Tadka", "description": "Yellow lentils tempered with ghee, garlic and red chillies", "category": "mains", "price": 275, "isVeg": true, "image": "https://source.unsplash.com/400x300/?dal+tadka,indian+food" },
        { "name": "Paneer Butter Masala", "description": "Rich and creamy paneer curry with buttery tomato gravy", "category": "mains", "price": 395, "isVeg": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?paneer+butter+masala,indian+food" },
        { "name": "Shahi Paneer", "description": "Royal paneer curry with creamy cashew and cream gravy", "category": "mains", "price": 405, "isVeg": true, "image": "https://source.unsplash.com/400x300/?shahi+paneer,indian+food" },
        { "name": "Kadhai Paneer", "description": "Paneer and peppers tossed in rustic kadhai masala", "category": "mains", "price": 385, "isVeg": true, "image": "https://source.unsplash.com/400x300/?kadhai+paneer,indian+food" },
        { "name": "Palak Paneer", "description": "Cottage cheese cubes in creamy spinach gravy with garlic", "category": "mains", "price": 375, "isVeg": true, "image": "https://source.unsplash.com/400x300/?palak+paneer,indian+food" },
        { "name": "Malai Kofta", "description": "Soft paneer and potato dumplings in rich creamy gravy", "category": "mains", "price": 395, "isVeg": true, "image": "https://source.unsplash.com/400x300/?malai+kofta,indian+food" },
        { "name": "Chana Masala", "description": "Chickpeas simmered in tangy onion-tomato masala", "category": "mains", "price": 295, "isVeg": true, "image": "https://source.unsplash.com/400x300/?chana+masala,indian+food" },
        { "name": "Rajma Masala", "description": "Red kidney beans in rich onion-tomato gravy with spices", "category": "mains", "price": 295, "isVeg": true, "image": "https://source.unsplash.com/400x300/?rajma+masala,indian+food" },
        { "name": "Bhindi Masala", "description": "Okra stir-fried with onions, tomatoes and Indian spices", "category": "mains", "price": 325, "isVeg": true, "image": "https://source.unsplash.com/400x300/?bhindi+masala,indian+food" },
        { "name": "Vegetable Kofta Curry", "description": "Mixed vegetable dumplings in rich tomato-onion gravy", "category": "mains", "price": 365, "isVeg": true, "image": "https://source.unsplash.com/400x300/?veg+kofta+curry,indian+food" },
        { "name": "Mushroom Masala", "description": "Button mushrooms in rich onion-tomato masala gravy", "category": "mains", "price": 355, "isVeg": true, "image": "https://source.unsplash.com/400x300/?mushroom+masala,indian+food" },
        { "name": "Methi Malai Chicken", "description": "Chicken in creamy fenugreek and cashew gravy", "category": "mains", "price": 495, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?methi+malai+chicken,indian+food" },

        // Breads
        { "name": "Plain Naan", "description": "Classic leavened bread baked in tandoor", "category": "breads", "price": 95, "isVeg": true, "image": "https://source.unsplash.com/400x300/?plain+naan,indian+food" },
        { "name": "Butter Naan", "description": "Soft naan brushed with melted butter", "category": "breads", "price": 115, "isVeg": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?butter+naan,indian+food" },
        { "name": "Garlic Naan", "description": "Tandoor-baked naan rubbed with garlic and butter", "category": "breads", "price": 145, "isVeg": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?garlic+naan,indian+food" },
        { "name": "Cheese Naan", "description": "Naan stuffed with melted cheese and herbs", "category": "breads", "price": 195, "isVeg": true, "image": "https://source.unsplash.com/400x300/?cheese+naan,indian+food" },
        { "name": "Tandoori Roti", "description": "Whole wheat bread baked in clay oven", "category": "breads", "price": 75, "isVeg": true, "image": "https://source.unsplash.com/400x300/?tandoori+roti,indian+food" },
        { "name": "Butter Roti", "description": "Whole wheat bread brushed with butter", "category": "breads", "price": 85, "isVeg": true, "image": "https://source.unsplash.com/400x300/?butter+roti,indian+food" },
        { "name": "Missi Roti", "description": "Spiced gram flour flatbread with ajwain and chillies", "category": "breads", "price": 105, "isVeg": true, "image": "https://source.unsplash.com/400x300/?missi+roti,indian+food" },
        { "name": "Roomali Roti", "description": "Paper-thin handkerchief bread cooked on inverted wok", "category": "breads", "price": 95, "isVeg": true, "image": "https://source.unsplash.com/400x300/?roomali+roti,indian+food" },
        { "name": "Laccha Paratha", "description": "Layered whole wheat paratha cooked with ghee", "category": "breads", "price": 125, "isVeg": true, "image": "https://source.unsplash.com/400x300/?laccha+paratha,indian+food" },
        { "name": "Pudina Paratha", "description": "Whole wheat paratha stuffed with fresh mint", "category": "breads", "price": 135, "isVeg": true, "image": "https://source.unsplash.com/400x300/?pudina+paratha,indian+food" },
        { "name": "Aloo Paratha", "description": "Whole wheat paratha stuffed with spiced potatoes", "category": "breads", "price": 145, "isVeg": true, "image": "https://source.unsplash.com/400x300/?aloo+paratha,indian+food" },
        { "name": "Paneer Paratha", "description": "Paratha stuffed with spiced cottage cheese", "category": "breads", "price": 175, "isVeg": true, "image": "https://source.unsplash.com/400x300/?paneer+paratha,indian+food" },
        { "name": "Gobi Paratha", "description": "Paratha stuffed with spiced cauliflower", "category": "breads", "price": 145, "isVeg": true, "image": "https://source.unsplash.com/400x300/?gobi+paratha,indian+food" },
        { "name": "Onion Kulcha", "description": "Leavened bread stuffed with spiced onions", "category": "breads", "price": 155, "isVeg": true, "image": "https://source.unsplash.com/400x300/?onion+kulcha,indian+food" },
        { "name": "Amritsari Kulcha", "description": "Punjabi stuffed kulcha with spiced potato filling", "category": "breads", "price": 185, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?amritsari+kulcha,indian+food" },
        { "name": "Masala Kulcha", "description": "Kulcha topped with spices and fresh coriander", "category": "breads", "price": 165, "isVeg": true, "image": "https://source.unsplash.com/400x300/?masala+kulcha,indian+food" },
        { "name": "Cheese Garlic Naan", "description": "Naan stuffed with cheese and topped with garlic butter", "category": "breads", "price": 215, "isVeg": true, "image": "https://source.unsplash.com/400x300/?cheese+garlic+naan,indian+food" },
        { "name": "Methi Paratha", "description": "Whole wheat paratha with fenugreek leaves", "category": "breads", "price": 135, "isVeg": true, "image": "https://source.unsplash.com/400x300/?methi+paratha,indian+food" },
        { "name": "Bajra Roti", "description": "Traditional pearl millet flatbread", "category": "breads", "price": 95, "isVeg": true, "image": "https://source.unsplash.com/400x300/?bajra+roti,indian+food" },
        { "name": "Makki Di Roti", "description": "Punjabi cornmeal flatbread served with white butter", "category": "breads", "price": 115, "isVeg": true, "image": "https://source.unsplash.com/400x300/?makki+roti,indian+food" },

        // Rice & Biryani
        { "name": "Chicken Biryani", "description": "Fragrant basmati rice layered with spiced chicken and saffron", "category": "rice-biryani", "price": 495, "isVeg": false, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?chicken+biryani,indian+food" },
        { "name": "Mutton Biryani", "description": "Royal Hyderabad-style biryani with tender mutton pieces", "category": "rice-biryani", "price": 595, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?mutton+biryani,indian+food" },
        { "name": "Hyderabadi Chicken Biryani", "description": "Authentic Hyderabadi dum biryani with saffron and mint", "category": "rice-biryani", "price": 525, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?hyderabadi+biryani,indian+food" },
        { "name": "Lucknowi Mutton Biryani", "description": "Awadhi-style mutton biryani with aromatic spices", "category": "rice-biryani", "price": 625, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?lucknowi+biryani,indian+food" },
        { "name": "Kolkata Chicken Biryani", "description": "Bengali-style biryani with potato and egg", "category": "rice-biryani", "price": 495, "isVeg": false, "image": "https://source.unsplash.com/400x300/?kolkata+biryani,indian+food" },
        { "name": "Vegetable Biryani", "description": "Aromatic basmati rice with mixed vegetables and biryani spices", "category": "rice-biryani", "price": 395, "isVeg": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?veg+biryani,indian+food" },
        { "name": "Paneer Biryani", "description": "Fragrant rice layered with spiced paneer and saffron", "category": "rice-biryani", "price": 425, "isVeg": true, "image": "https://source.unsplash.com/400x300/?paneer+biryani,indian+food" },
        { "name": "Egg Biryani", "description": "Flavorful rice with spiced boiled eggs and fried onions", "category": "rice-biryani", "price": 375, "isVeg": false, "image": "https://source.unsplash.com/400x300/?egg+biryani,indian+food" },
        { "name": "Prawn Biryani", "description": "Coastal-style biryani with succulent prawns and spices", "category": "rice-biryani", "price": 625, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?prawn+biryani,indian+food" },
        { "name": "Awadhi Biryani", "description": "Royal Awadhi dum biryani with saffron and kewra", "category": "rice-biryani", "price": 575, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?awadhi+biryani,indian+food" },
        { "name": "Jeera Rice", "description": "Steamed basmati rice tempered with cumin seeds", "category": "rice-biryani", "price": 225, "isVeg": true, "image": "https://source.unsplash.com/400x300/?jeera+rice,indian+food" },
        { "name": "Steamed Basmati Rice", "description": "Fluffy steamed basmati rice", "category": "rice-biryani", "price": 195, "isVeg": true, "image": "https://source.unsplash.com/400x300/?steamed+rice,indian+food" },
        { "name": "Peas Pulao", "description": "Basmati rice cooked with green peas and whole spices", "category": "rice-biryani", "price": 245, "isVeg": true, "image": "https://source.unsplash.com/400x300/?peas+pulao,indian+food" },
        { "name": "Vegetable Pulao", "description": "Lightly spiced rice with garden vegetables and whole spices", "category": "rice-biryani", "price": 265, "isVeg": true, "image": "https://source.unsplash.com/400x300/?veg+pulao,indian+food" },
        { "name": "Kashmiri Pulao", "description": "Fragrant rice with dry fruits, saffron and rose water", "category": "rice-biryani", "price": 325, "isVeg": true, "image": "https://source.unsplash.com/400x300/?kashmiri+pulao,indian+food" },
        { "name": "Saffron Rice", "description": "Basmati rice infused with saffron and ghee", "category": "rice-biryani", "price": 345, "isVeg": true, "image": "https://source.unsplash.com/400x300/?saffron+rice,indian+food" },
        { "name": "Mushroom Pulao", "description": "Basmati rice with mushrooms and whole spices", "category": "rice-biryani", "price": 295, "isVeg": true, "image": "https://source.unsplash.com/400x300/?mushroom+pulao,indian+food" },
        { "name": "Chicken Pulao", "description": "Fragrant rice cooked with chicken and whole spices", "category": "rice-biryani", "price": 425, "isVeg": false, "image": "https://source.unsplash.com/400x300/?chicken+pulao,indian+food" },
        { "name": "Mutton Pulao", "description": "Aromatic rice with tender mutton and whole spices", "category": "rice-biryani", "price": 525, "isVeg": false, "image": "https://source.unsplash.com/400x300/?mutton+pulao,indian+food" },
        { "name": "Lemon Rice", "description": "South Indian style rice with lemon, peanuts and curry leaves", "category": "rice-biryani", "price": 235, "isVeg": true, "image": "https://source.unsplash.com/400x300/?lemon+rice,indian+food" },

        // Desserts
        { "name": "Gulab Jamun", "description": "Deep-fried milk dumplings soaked in rose-scented sugar syrup", "category": "desserts", "price": 165, "isVeg": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?gulab+jamun,indian+food" },
        { "name": "Rasmalai", "description": "Soft paneer discs soaked in sweetened saffron-infused milk", "category": "desserts", "price": 195, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?rasmalai,indian+food" },
        { "name": "Gajar Ka Halwa", "description": "Traditional carrot halwa slow-cooked with ghee and milk", "category": "desserts", "price": 185, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?gajar+halwa,indian+food" },
        { "name": "Kulfi", "description": "Traditional Indian ice cream with cardamom and nuts", "category": "desserts", "price": 155, "isVeg": true, "image": "https://source.unsplash.com/400x300/?kulfi,indian+food" },
        { "name": "Kesar Kulfi", "description": "Saffron-infused Indian ice cream with pistachios", "category": "desserts", "price": 185, "isVeg": true, "image": "https://source.unsplash.com/400x300/?kesar+kulfi,indian+food" },
        { "name": "Mango Kulfi", "description": "Creamy mango-flavored Indian ice cream", "category": "desserts", "price": 175, "isVeg": true, "image": "https://source.unsplash.com/400x300/?mango+kulfi,indian+food" },
        { "name": "Jalebi", "description": "Crispy spiral sweets soaked in saffron syrup", "category": "desserts", "price": 145, "isVeg": true, "image": "https://source.unsplash.com/400x300/?jalebi,indian+food" },
        { "name": "Rabri Jalebi", "description": "Crispy jalebis served with thick sweetened milk", "category": "desserts", "price": 225, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?rabri+jalebi,indian+food" },
        { "name": "Shahi Tukda", "description": "Royal bread pudding with saffron and dry fruits", "category": "desserts", "price": 195, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?shahi+tukda,indian+food" },
        { "name": "Phirni", "description": "Creamy ground rice pudding with cardamom and saffron", "category": "desserts", "price": 175, "isVeg": true, "image": "https://source.unsplash.com/400x300/?phirni,indian+food" },
        { "name": "Kheer", "description": "Traditional rice pudding with nuts and cardamom", "category": "desserts", "price": 165, "isVeg": true, "image": "https://source.unsplash.com/400x300/?kheer,indian+food" },
        { "name": "Rasgulla", "description": "Soft spongy cottage cheese balls in sugar syrup", "category": "desserts", "price": 155, "isVeg": true, "image": "https://source.unsplash.com/400x300/?rasgulla,indian+food" },
        { "name": "Moong Dal Halwa", "description": "Rich lentil halwa slow-cooked with ghee and saffron", "category": "desserts", "price": 195, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?moong+dal+halwa,indian+food" },
        { "name": "Malpua", "description": "Crispy pancakes soaked in sugar syrup with nuts", "category": "desserts", "price": 185, "isVeg": true, "image": "https://source.unsplash.com/400x300/?malpua,indian+food" },
        { "name": "Rabri", "description": "Thickened sweetened milk with cardamom and nuts", "category": "desserts", "price": 175, "isVeg": true, "image": "https://source.unsplash.com/400x300/?rabri,indian+food" },
        { "name": "Besan Ladoo", "description": "Gram flour sweets with ghee and cardamom", "category": "desserts", "price": 145, "isVeg": true, "image": "https://source.unsplash.com/400x300/?besan+ladoo,indian+food" },
        { "name": "Coconut Ladoo", "description": "Sweet coconut balls with condensed milk", "category": "desserts", "price": 145, "isVeg": true, "image": "https://source.unsplash.com/400x300/?coconut+ladoo,indian+food" },
        { "name": "Chocolate Gulab Jamun", "description": "Classic gulab jamun with molten chocolate center", "category": "desserts", "price": 195, "isVeg": true, "image": "https://source.unsplash.com/400x300/?chocolate+gulab+jamun,indian+food" },
        { "name": "Matka Kulfi", "description": "Traditional kulfi served in clay pot with pistachios", "category": "desserts", "price": 225, "isVeg": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?matka+kulfi,indian+food" },
        { "name": "Saffron Phirni", "description": "Royal saffron phirni with slivered almonds", "category": "desserts", "price": 215, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?saffron+phirni,indian+food" },

        // Specials
        { "name": "Royal Thali", "description": "Complete royal feast with dal, paneer, roti, rice, and dessert", "category": "specials", "price": 895, "isVeg": true, "isChefSpecial": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?royal+thali,indian+food" },
        { "name": "Chef's Special Butter Chicken", "description": "Signature butter chicken with chef's secret spice blend", "category": "specials", "price": 695, "isVeg": false, "isChefSpecial": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?chef+butter+chicken,indian+food" },
        { "name": "Signature Mutton Rogan Josh", "description": "Slow-cooked Kashmiri lamb curry with royal spices", "category": "specials", "price": 795, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?signature+rogan+josh,indian+food" },
        { "name": "Royal Chicken Biryani", "description": "Dum-cooked biryani with saffron, kewra and tender chicken", "category": "specials", "price": 725, "isVeg": false, "isChefSpecial": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?royal+chicken+biryani,indian+food" },
        { "name": "Special Paneer Tikka", "description": "Premium paneer tikka with truffle oil and exotic spices", "category": "specials", "price": 525, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?special+paneer+tikka,indian+food" },
        { "name": "Truffle Mushroom Curry", "description": "Wild mushrooms in rich truffle-infused creamy gravy", "category": "specials", "price": 595, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?truffle+mushroom+curry,indian+food" },
        { "name": "Smoked Dal Makhani", "description": "Black lentils slow-cooked and finished with smoke", "category": "specials", "price": 425, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?smoked+dal+makhani,indian+food" },
        { "name": "Awadhi Mutton Korma", "description": "Royal Awadhi mutton curry with cashew and saffron", "category": "specials", "price": 795, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?awadhi+mutton+korma,indian+food" },
        { "name": "Tandoori Lamb Chops", "description": "Lamb chops marinated in royal spices, chargrilled", "category": "specials", "price": 895, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?tandoori+lamb+chops,indian+food" },
        { "name": "Royal Prawn Curry", "description": "Jumbo prawns in rich coconut and spice gravy", "category": "specials", "price": 795, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?royal+prawn+curry,indian+food" },
        { "name": "Saffron Chicken Korma", "description": "Chicken in creamy saffron and cashew korma", "category": "specials", "price": 695, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?saffron+chicken+korma,indian+food" },
        { "name": "Charcoal Chicken Tikka", "description": "Chicken tikka grilled over charcoal with smoky flavor", "category": "specials", "price": 625, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?charcoal+chicken+tikka,indian+food" },
        { "name": "Signature Galouti Kebab", "description": "Melt-in-mouth galouti kebabs with royal Awadhi spices", "category": "specials", "price": 675, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?signature+galouti+kebab,indian+food" },
        { "name": "Lucknowi Chicken Korma", "description": "Awadhi-style chicken korma with aromatic spices", "category": "specials", "price": 595, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?lucknowi+chicken+korma,indian+food" },
        { "name": "Rajasthani Laal Maas", "description": "Fiery Rajasthani lamb curry with Mathania chillies", "category": "specials", "price": 795, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?rajasthani+laal+maas,indian+food" },
        { "name": "Kashmiri Yakhni", "description": "Delicate Kashmiri yogurt-based lamb curry", "category": "specials", "price": 695, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?kashmiri+yakhni,indian+food" },
        { "name": "Chef's Special Paneer", "description": "Premium paneer dish with chef's signature sauce", "category": "specials", "price": 525, "isVeg": true, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?chef+paneer,indian+food" },
        { "name": "Royal Seafood Platter", "description": "Assorted seafood delicacies with royal accompaniments", "category": "specials", "price": 1195, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?seafood+platter,indian+food" },
        { "name": "Grand Mughlai Platter", "description": "Grand assortment of Mughlai delicacies", "category": "specials", "price": 995, "isVeg": false, "isChefSpecial": true, "image": "https://source.unsplash.com/400x300/?mughlai+platter,indian+food" },
        { "name": "Signature Biryani Platter", "description": "Signature biryani served with royal accompaniments", "category": "specials", "price": 895, "isVeg": false, "isChefSpecial": true, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?signature+biryani+platter,indian+food" }
    ],
    "drinks": [
        { "name": "Mint Cooler", "description": "Refreshing mint and lime cooler with a touch of honey", "category": "mocktails", "price": 199, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?mint+cooler,indian+food" },
        { "name": "Mango Lassi", "description": "Thick creamy yogurt drink with mango pulp", "category": "lassi-shakes", "price": 179, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?mango+lassi,indian+food" },
        { "name": "Masala Chai", "description": "Traditional Indian spiced tea with ginger and cardamom", "category": "hot-beverages", "price": 99, "isBestSeller": true, "image": "https://source.unsplash.com/400x300/?masala+chai,indian+food" }
    ],
    "tables": [
        { "tableNumber": 1, "capacity": 2, "section": "indoor", "isActive": true },
        { "tableNumber": 2, "capacity": 2, "section": "indoor", "isActive": true },
        { "tableNumber": 3, "capacity": 4, "section": "indoor", "isActive": true },
        { "tableNumber": 4, "capacity": 4, "section": "indoor", "isActive": true },
        { "tableNumber": 5, "capacity": 4, "section": "indoor", "isActive": true },
        { "tableNumber": 6, "capacity": 6, "section": "indoor", "isActive": true },
        { "tableNumber": 7, "capacity": 2, "section": "outdoor", "isActive": true },
        { "tableNumber": 8, "capacity": 2, "section": "outdoor", "isActive": true },
        { "tableNumber": 9, "capacity": 4, "section": "outdoor", "isActive": true },
        { "tableNumber": 10, "capacity": 4, "section": "outdoor", "isActive": true },
        { "tableNumber": 11, "capacity": 6, "section": "outdoor", "isActive": true },
        { "tableNumber": 12, "capacity": 2, "section": "private", "isActive": true },
        { "tableNumber": 13, "capacity": 4, "section": "private", "isActive": true },
        { "tableNumber": 14, "capacity": 4, "section": "private", "isActive": true },
        { "tableNumber": 15, "capacity": 2, "section": "private", "isActive": true }
    ],
    "awards": [
        { "title": "Best North Indian Restaurant", "platform": "Zomato", "year": 2024, "description": "Awarded for exceptional dining experience" },
        { "title": "Top Rated Fine Dining", "platform": "Google", "year": 2024, "description": "4.8 stars from 2000+ reviews" },
        { "title": "Excellence in Service", "platform": "Swiggy", "year": 2023, "description": "Outstanding hospitality" },
        { "title": "Best Ambiance Award", "platform": "EazyDiner", "year": 2024, "description": "Warm and inviting atmosphere" }
    ],
    "reviews": [
        { "reviewerName": "Priya Sharma", "platform": "Zomato", "rating": 5, "comment": "The butter chicken is divine!", "isVerified": true },
        { "reviewerName": "Rahul Mehta", "platform": "Google", "rating": 5, "comment": "Best North Indian dining experience.", "isVerified": true },
        { "reviewerName": "Ananya Patel", "platform": "Swiggy", "rating": 4, "comment": "The Sunday brunch buffet is incredible.", "isVerified": true },
        { "reviewerName": "Vikram Singh", "platform": "Zomato", "rating": 5, "comment": "Exquisite flavors and impeccable service.", "isVerified": true }
    ],
    "adminUser": { "email": "admin@renorth.com", "name": "Admin", "role": "admin" }
};
